author: Krzysztof Begiedza
title: Blog - Krzysztof Begiedza
description: Blog - Krzysztof Begiedza
encoding: utf-8
mode: dark

permalink: /:title

sass:
    style: compressed

number_of_posts: 5

# Markdown stuff
markdown: kramdown
highlighter: rouge
kramdown:
    input: GFM
    syntax_highlighter: rouge
    math_engine: mathjax

# Collections dir
collections_dir: tutorials
collections:
    one:
        output: true
        permalink: /:collection/:title

plugins:
    - jekyll-feed
    - jekyll-sitemap

exclude:
    - "CNAME"
    - "Dockerfile"
    - "README.md"
